version: '2'
services:
  app:
    extends:
      file: docker-compose.common.yml
      service: app
    links:
      - db
    environment:
      - DB_HOST=db

  db:
    extends:
      file: docker-compose.common.yml
      service: db
